BOARD = zedboard
UBOOT_CONFIG = zed
BOARD_MODEL = em.avnet.com:zed:part0:1.0
PART = xc7z020clg484-1
# CONFIG is the target configuration for the rocket-chip generator
CONFIG ?= DefaultFPGAConfig

include ../common/Makefrag
