BOARD = zedboard
UBOOT_CONFIG = zed
BOARD_MODEL = em.avnet.com:zed:part0:1.0
PART = xc7z020clg484-1
# CONFIG_PROJECT designates the scala project in which the config is defined
# This is useful when specifying a configuration already present in rocketchip
CONFIG_PROJECT ?= rocketchip
# CONFIG is the target configuration for the rocket-chip generator
CONFIG ?= DefaultFPGAConfig

include ../common/Makefrag
