BOARD = zybo
UBOOT_CONFIG = $(BOARD)
PART = xc7z010clg400-1
# CONFIG_PROJECT designates the scala project in which the config is defined
# This is useful when specifying a configuration already present in rocketchip
CONFIG_PROJECT ?= rocketchip
# CONFIG is the target configuration for the rocket-chip generator
CONFIG ?= DefaultFPGASmallConfig

include ../common/Makefrag
