BOARD = zybo
UBOOT_CONFIG = $(BOARD)
PART = xc7z010clg400-1
# CFG_PROJECT is the scala project in which the configuration is defined
CFG_PROJECT ?= rocketchip
# CONFIG is the target configuration for the rocket-chip generator
CONFIG ?= DefaultFPGASmallConfig

include ../common/Makefrag
