BOARD = zc706_MIG
UBOOT_CONFIG = zc70x
BOARD_MODEL = xilinx.com:zc706:part0:1.0
PART = xc7z045ffg900-2
# CFG_PROJECT is the scala project in which the configuration is defined
CFG_PROJECT ?= zynq
# CONFIG is the target configuration for the rocket-chip generator
CONFIG ?= ZC706MIGConfig

include ../common/Makefrag
