BOARD = zc706
UBOOT_CONFIG = zc70x
BOARD_MODEL = xilinx.com:zynq:zc706:1.1
PART = xc7z045ffg900-2
# CONFIG is the target configuration for the rocket-chip generator
CONFIG ?= DaisyFPGAConfig

include ../common/Makefrag
